//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShilinWpf.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectID { get; set; }
        public string Description { get; set; }
        public int ClientsID { get; set; }
        public int WorkerID { get; set; }
        public int AssetsID { get; set; }
        public int TypeServiceID { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual Client Client { get; set; }
        public virtual TypeService TypeService { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
