//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShilinWpf.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public string ProjectID { get; set; }
        public string Name { get; set; }
        public string ClientsID { get; set; }
        public string WorkerID { get; set; }
        public string AssetsID { get; set; }
        public string TypeServiceID { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual Client Client { get; set; }
        public virtual TypeService TypeService { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
