//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorbitWpf.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectID { get; set; }
        public string Description { get; set; }
        public int ClientsID { get; set; }
        public int WorkerID { get; set; }
        public int AssetsID { get; set; }
        public int TypeServiceID { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual Client Client { get; set; }
        public virtual TypeService TypeService { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
